# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tkkbkn's blog
email: canhld94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Khi còn nhỏ, chúng ta nghĩ cần phải dũng cảm để chiến thắng người khác. Khi trưởng thành, chúng ta hiểu ra cần dũng cảm để chiến thắng chính bản thân mình. Đây là blog của một người dũng cảm. 
  
  This is a brave man's blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://canhld94.github.io" # the base hostname & protocol for your site
github_username:  canhld94
leetcode_username: canhld94

# Build settings
# gems:
#   - jekyll-paginate
# paginate: 5
markdown: kramdown
kramdown:
  hard_wrap: true

excerpt_separator: "<!-- more -->"

max_excerpt_len: 100

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true