# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tkkbkn's blog
email: canhld94@gmail.com
cv: https://www.dropbox.com/s/uu074t2o1lgkf8l/canh_cv.pdf?dl=0
wordpress: https://tkkbkn.wordpress.com/
description: > # this means to ignore newlines until "baseurl:"
  Khi còn nhỏ, chúng ta nghĩ cần phải dũng cảm để chiến thắng người khác. Khi trưởng thành, chúng ta hiểu ra cần dũng cảm để chiến thắng chính bản thân mình. Đây là blog của một người dũng cảm. 
  
  This is a brave man's blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://canhld94.github.io" # the base hostname & protocol for your site
github_username:  canhld94
leetcode_username: canhld94

# Build settings
# gems:
#   - jekyll-paginate
# paginate: 5
markdown: kramdown
kramdown:
  hard_wrap: true
highlighter: rouge

excerpt_separator: "<!-- more -->"

max_excerpt_len: 100

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true


# Resume settings
resume_avatar:                  "false"
resume_name:                    "Duc Canh Le"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "canhld94@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-9872-8980"
resume_contact_address:         "E3-2, #3211, KAIST, Daejeon, Korea"

resume_header_contact_info:     "E3-2, #3211, KAIST, Daejeon, Korea • 010-9872-8980 • canhld94@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi, I am Duc Canh Le from Vietnam. I love computers and everything about it except Window update. I'm on my way to becoming a senior software developer to make software faster and more reliable to users.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/canhld94"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://canhld94.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server star